backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

publish_mode: "editorial_workflow"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blogpost" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    media_folder: "static/images"
    public_folder: "/images"
    path: "{{slug}}"
    view_filters:
      - label: Posts With Index
        field: title
        pattern: "This is post #"
      - label: Posts Without Index
        field: title
        pattern: front matter post
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          dateFormat: "YYYY-MM-DD",
          timeFormat: false,
          format: "YYYY-MMM-D",
        }
      - {
          label: "Slug",
          name: "slug",
          required: true,
          widget: "string",
          hint: "remember-to-use-lowercase-and-dashes",
        }
      - {
          label: "Cover Image",
          name: "image",
          widget: "image",
          required: false,
          tagname: "",
        }
      - { label: "Blogpost content", name: "body", widget: "markdown" }
