backend:
  name: git-gateway
  branch: main
publish_mode: "editorial_workflow"
media_folder: "/images"
public_folder: "/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{slug}}"
    path: "{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD", timeFormat: false, format: "YYYY-MMM-D" }
      - { label: "Slug", name: "slug", required: true, widget: "string", hint: "remember-to-use-lowercase-and-dashes" }
      - { label: "Blogpost content", name: "body", widget: "markdown" }