---
backend:
  name: git-gateway
  branch: main
media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blogpost
    folder: src/pages/blog
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: /pages/blog/"{{title}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: false
        format: YYYY-MMM-D
      - label: Slug
        name: slug
        required: true
        widget: string
        hint: remember-to-use-lowercase-and-dashes
      - label: Blogpost content
        name: body
        widget: markdown
